# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "clients.baml": "// LLM client for the ReAct loop. Temperature is low — the agent must be\n// deterministic, not creative — and retries cover transient parse failures.\n// Routed through the LiteLLM proxy — cost tracking and fallback happen there.\nclient<llm> AgentLLM {\n  provider openai\n  retry_policy ReActRetry\n  options {\n    model env.LLM_CHAT_MODEL\n    api_key env.LITELLM_MASTER_KEY\n    base_url env.LITELLM_BASE_URL_LOCAL\n    temperature 0.1\n  }\n}\n\nretry_policy ReActRetry {\n  max_retries 2\n  strategy {\n    type constant_delay\n    delay_ms 200\n  }\n}\n",
    "generators.baml": "// BAML generator config — generated client lives in src/rag/agent/baml_client/.\ngenerator target {\n    output_type \"python/pydantic\"\n    output_dir \"../\"\n    version \"0.223.0\"\n    default_client_mode sync\n}\n",
    "react.baml": "// ReAct step contract: the LLM either reasons (Thought), calls a tool (Action),\n// or answers (FinalAnswer). Python orchestrates the loop in agent/react.py —\n// this file only defines the LLM-facing schema and prompt.\n\nclass Thought {\n  reasoning string\n  action_needed bool\n}\n\nclass Action {\n  tool_name string\n  tool_input string\n}\n\nclass FinalAnswer {\n  answer string\n  citations string[]\n}\n\nfunction ReActStep(query: string, context: string, history: string) -> Thought | Action | FinalAnswer {\n  client AgentLLM\n  prompt #\"\n    You are a RAG agent answering questions over a private Obsidian vault.\n\n    Given the query, the most recent retrieved context, and the reasoning\n    history so far, decide what to do next:\n\n    - If you need more information to answer the query, return an Action with\n      tool_name = \"vector_search\" and tool_input = the search query to run.\n    - If the retrieved context is sufficient to answer, return a FinalAnswer.\n      Always cite the source note filenames you relied on in `citations`.\n    - Otherwise, return a Thought explaining your reasoning before acting.\n\n    Never invent information that is not present in the retrieved context.\n    If the context does not contain the answer, say so in the FinalAnswer\n    rather than guessing.\n\n    Query: {{ query }}\n\n    Most recent retrieved context:\n    {{ context }}\n\n    Reasoning history so far:\n    {{ history }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n\ntest react_step_answers_with_sufficient_context {\n  functions [ReActStep]\n  args {\n    query \"What is the capital of France?\"\n    context \"note.md: Paris is the capital of France.\"\n    history \"\"\n  }\n}\n",
}

def get_baml_files():
    return _file_map