# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (3)
# #########################################################################

class Action(BaseModel):
    tool_name: typing.Optional[str] = None
    tool_input: typing.Optional[str] = None

class FinalAnswer(BaseModel):
    answer: typing.Optional[str] = None
    citations: typing.List[str]

class Thought(BaseModel):
    reasoning: typing.Optional[str] = None
    action_needed: typing.Optional[bool] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
